name: Create Weekly Issue

on:
  schedule:
    - cron: '14 9 * * 6'  # Runs at 3:14 PM IST on Saturday
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read current_link.txt
        id: read_link
        run: |
          echo "::set-output name=number::$(cat current_link.txt | cut -d'|' -f2)"


      - name: Create Issue
        uses: actions/github-script@v7
        with:
          script: |
            let issueNumber = ${{ steps.read_link.outputs.number }};
            issueNumber++;
            const issue = {
              title: `Nibble #${issueNumber} Content Checklist`,
              body: `This is an automated issue to track weekly tasks for Nibble #${issueNumber}.

              Primary Content Checklist:
              - [ ] AI
              - [ ] 0x
              - [ ] Dev & Design
              - [ ] WBUTA
              - [ ] TIL
              - [ ] WWHBT
              - [ ] Builder's Nest
              - [ ] Meme
              - [ ] Quote Of The Week
              - [ ] Wallpaper
              - [ ] Off Topic
              - [ ] Standup
                - [ ] A
                - [ ] P
              - [ ] Meta

              Meta Content Checklist:
              - [ ] Cover Image
              - [ ] NotebookLM Podcast
              - [ ] [latest.nibbles.dev](https://latest.nibbles.dev/) is updated?
              - [ ] Social Media Post`,
              labels: ['weekly-checklist']
            };

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ['aashutoshrathi', 'thepushkarp'],
              ...issue
            });
